### ISSUE TITLE
Unable to upload netscaler converted json to avi appliance

### ISSUE THREAD

**Issue by wewenttothemoon** [vmware/alb-sdk#1934] opened 2021-12-21 03:47 UTC
### Describe the bug

Hello, 
Reaching out because we are encountering another issue with the avi migration tools sdk for the netscaler converter tool. As previously advised, we are using the docker container on an ubuntu vm. However, when we run the tool to convert the ns.conf file into the json output and auto-upload into the avi appliance after a few minutes the operation seems to timeout and fail. Any further guidance you can provide to assist us with importing this config into the alb? From the ubuntu device we are able to ping the appliance, and browse to it on firefox, below is the error dump (obfuscated IP and password, btw using the admin account for cli access with the correct password) 
[ErrorOutput.odt](https://github.com/vmware/alb-sdk/files/7749404/ErrorOutput.odt)

### Reproduction steps

```bash
1.Run the following command sudo ./run.sh -c "netscaler_converter.py -f ns.conf -s disable -O auto-upload -c x.x.x.240 -u admin -p $a -t admin"
2.
3.
...
```

### Expected behavior

Expected for the JSON file generated to be successfully uploaded into the ALB

**Comment by chaitanyaavi** [comment] 2022-02-14 05:35
@wewenttothemoon Can you please create a Support case with VMWare with sharing the ns.conf file We are not able to reproduce it with our configs. The workaround could be migrating with --ansible flag and using Ansible scripts generated in migration to configure Avi Controller.

**Comment by chaitanyaavi** [comment] 2022-05-09 22:00
No reply hence closing it

**Closed as completed by chaitanyaavi** 2022-05-09 22:00 UTC
Labels: bug
